version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3.8.16-management"
    container_name: rabbitmq
    hostname: "rabbitmq"
    environment:
      # RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "15692:15692"
      - "5672:5672"
    # volumes:
    #   - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
